FROM node:6.10

# yarn
RUN apt-get update && apt-get -y install apt-transport-https
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update && apt-get -y install yarn

# working directory
ADD ./ /code
WORKDIR /code

# init node modules
RUN npm install -g --silent node-gyp
RUN npm install -g --silent mocha
RUN yarn install
