FROM node:alpine

# yarn + ssh
ENV PATH /root/.yarn/bin:$PATH
RUN apk update \
  && apk add curl bash binutils tar openssh \
  && rm -rf /var/cache/apk/* \
  && /bin/bash \
  && touch ~/.bashrc \
  && curl -o- -L https://yarnpkg.com/install.sh | bash \
  && apk del curl tar binutils


# working directory
ADD ./ /code
WORKDIR /code

# init node modules
RUN npm install -g --silent mocha
RUN yarn install
